### ISSUE TITLE
-end-req do not work as expected.

### ISSUE THREAD

**Issue by teyssieuman** [goeb/reqflow#12]
Here is my document : 

```
= Specification bla bla bla.

The  bla bla bla bla bla bla. 
Since  bla bla bla bla bla bla bla bla bla. 

NOTE: The **bla bla bla** system will be refered as **bla bla bla**.

{REQ_S0_001-RC} bla bla bla bla bla bla bla bla bla bla bla bla.#

{REQ_S0_002-DMS} The  bla bla bla shall be design in such a way that  bla bla bla.
    As well as in tre req {REQ_S0_001-RC}.#

```

And this is my "req" configuration file:

```
document SPEC -path SPEC1.md \
	-req "{(REQ_[-a-zA-Z0-9_]*)}" \
    -end-req "#" \
	-stop-after Annex
```

This lead to an error : 

> SPEC:REQ_S0_001-RC: Duplicate requirement: also defined in 'SPEC1.md'

As I understand the "-end-req" option reqflow should consider that the requirement extends until the "#".

**Comment by goeb** [comment]
You encounter here some limitations of reqflow and I suggest some adaptations in your document.

1. The capture of the requirements identifiers do not consider the option "-end-req" (see below), and consequently REQ_S0_001-RC is encountered twice and considered as a duplicated requirement id.
I would suggest that you remove the brackets around the second occurrence, and it will no longer be captured as a requirement.


2. The "-end-req" option is only used for capturing the text of the requirement, and has currently the following limitation: the text on the same line as the end-req pattern (#) is not taken. The reason is that text files are processed line by line.

If you do not need to capture the text, you do not need the -end-req, nor the #, at all.

If you need to capture the text (used when you run "reqflow review"):
- either put the # on a separate line after the text of the requirement
- or do not use -end-req, nor # at all (the text stops when the next requirement starts)

I will update the documentation.
