### ISSUE TITLE
requirement traceability agains code

### ISSUE THREAD

**Issue by herve0026** [goeb/reqflow#15]
hello, 
thanks first for this software. 
I was wondering if it could be possible to implement req traceability between spec document and code files.
It is slightly different from req traceability between spec doc and test doc cause in source files there will only be references to requirements.
Regards.

**Comment by goeb** [comment]
Hello,
Reqflow needs an identifier in the code so that it can associate the spec requirements with that identifier.

If you can modify the code that you want to analyse, you can add identifiers, like in this C language example (identifiers starting by "CODE_"):

```
/* CODE_PRINT_HELP
 * ref: PRINTF_01 */
int print_help()
{
    ...
}

/* CODE_PARSE_FORMAT_STRING
 * ref: PRINTF_02 */
int parse_format_string()
{
    ...
}
```

If you cannot modify the code (eg: legacy code, or code being audited), you could try to cheat and pretend that one of the first lines is the identifier for the whole file. For example if all files start with a Copyright line, use a configuration file like this:

```
document CODE_printf -path printf.c -prefix-req printf -req "Copyright" -ref "ref: (PRINTF_[0-9]+)" -nocov
document CODE_file2 -path file2.c -prefix-req file2 -req "Copyright" -ref "ref: (PRINTF_[0-9]+)" -nocov
document CODE_file3 -path file3.c -prefix-req file3 -req "Copyright" -ref "ref: (PRINTF_[0-9]+)" -nocov
```

But this remains a "hack".

**Comment by herve0026** [comment]
Thanks for the reply !
I'm gonna try these advices.
